sync:
  # NOTES
  # - use an image with digest for the source (use `crane digest IMAGE_REF` to find it); ensuring the exact image is used and the tag can't be swapped underneath
  - source: docker.io/library/alpine:3.18@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
    destination: ghcr.io/geonet/base-images/alpine:3.18 # latest alpine
  - source: docker.io/redhat/ubi8-minimal:8.8@sha256:621f5245fb3e8597a626163cdf1229e1f8311e07ab71bb1e9332014b51c59f9c
    destination: ghcr.io/geonet/base-images/ubi8-minimal:8.8
  - source: docker.io/datadog/agent:7@sha256:b9e11fd44fec2dc6f42d7d8eeafb29dc16bc185af37c395b9c3864b1402134d0
    destination: ghcr.io/geonet/base-images/datadog/agent:7
  - source: docker.io/library/debian:bullseye@sha256:432f545c6ba13b79e2681f4cc4858788b0ab099fc1cca799cc0fae4687c69070
    destination: ghcr.io/geonet/base-images/debian:bullseye
  - source: docker.io/hadolint/hadolint:v2.12.0-alpine@sha256:3c206a451cec6d486367e758645269fd7d696c5ccb6ff59d8b03b0e45268a199
    destination: ghcr.io/geonet/base-images/hadolint/hadolint:v2.12.0-alpine
  - source: docker.io/hashicorp/terraform:1.4@sha256:1ab70aa9b5dcc007d1d908c972405e2623490a51843a500682809013a4d21699
    destination: ghcr.io/geonet/base-images/hashicorp/terraform:1.4
  - source: docker.io/library/node:16.17.1-alpine@sha256:4d68856f48be7c73cd83ba8af3b6bae98f4679e14d1ff49e164625ae8831533a # older node
    destination: ghcr.io/geonet/base-images/node:16.17.1-alpine
  - source: docker.io/library/node:20-bullseye@sha256:14f0471d0478fbb9177d0f9e8c146dc872273dcdcfc7fea93a27ed81fc6b0e96
    destination: ghcr.io/geonet/base-images/node:bullseye
  - source: docker.io/library/python:3.11.3-bullseye@sha256:13927a8172d13b6cdc87f50bf0a38ff4eceef05262f83870c9f6474d16117687
    destination: ghcr.io/geonet/base-images/python:3.11.3-bullseye
  - source: docker.io/library/python:alpine3.16@sha256:9efc6e155f287eb424ede74aeff198be75ae04504b1e42e87ec9f221e7410f2d
    destination: ghcr.io/geonet/base-images/python:alpine3.16
  - source: cgr.dev/chainguard/go:latest@sha256:829594acdbc0f50ea5cae9ae208224999c21d1ee3dfe8003b177814056a827f1
    destination: ghcr.io/geonet/base-images/go-scratch:latest
  - source: cgr.dev/chainguard/static:latest@sha256:da9822ad6f973e40e24e75133b08ae874900766873ecd03e58f7f630ccea898c
    destination: ghcr.io/geonet/base-images/static:latest
  - source: cgr.dev/chainguard/nginx:latest@sha256:8c05680b8a70b49013f9011cba5b50b26683e3360280a6065d30ef0cd8a50524
    destination: ghcr.io/geonet/base-images/nginx:latest
  - source: cgr.dev/chainguard/node:20@sha256:38dc35af8d4bd8f59c1d8b88999e7dee9746dcee0f375848fb9701f3b61564e5 # latest node
    destination: ghcr.io/geonet/base-images/node:20
  - source: ghcr.io/geonet/base-images/mkdocs_plus:latest@sha256:d54c497b4ec5cce0c41b84e6afe5e4250c0b6ba499832ee977137f0f5e9c8a77
    destination: ghcr.io/geonet/base-images/mkdocs_plus:2023-06-14

build:
  # NOTES
  # - uses dirname of source as context for build
  # - image.yaml for apko based build
  # - Dockerfile for Docker based build
  # - structure like ./images/IMAGE_NAME/...
  # - images are pushed to ghcr.io/geonet/base-images/IMAGE_NAME
  - source: ./images/mkdocs_plus/Dockerfile
    destination: ghcr.io/geonet/base-images/mkdocs_plus:latest
  - source: ./images/git/image.yaml
    destination: ghcr.io/geonet/base-images/git:latest
  - source: ./images/texlive/image.yaml
    destination: ghcr.io/geonet/base-images/texlive:latest
