name: images are public
on:
  push:
    branches:
      - main
jobs:
  images-are-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      - uses: GeoNet/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # main
      - name: check images are public
        run: |
          # NOTE: important to not use auth
          jq -r -c '.sync as $sync | .build as $build | {"include":[{"destination": $sync[].destination}, {"destination": $build[].destination}]} | .include[] | select(.destination | contains("amazonaws.com") | not) | .destination' <<< "$(yq e . -o json config.yaml)" \
            | xargs -n 1 -I{} crane digest {}
