name: presubmit image documented
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  presubmit-image-documented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: GeoNet/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # main
      - name: resolve image to digest
        run: |
          FAILURES=false
          for IMAGE in $(jq -r -c '.sync as $sync | .build as $build | [{"destination": $sync[].destination}, {"destination": $build[].destination}] | .[].destination'  <<< "$(yq e . -o json config.yaml)" | cut -d ':' -f1 | sort | uniq); do
            if ! grep -q -E "(^| )$IMAGE( |$)" README.md; then
              echo "Not found in README: $IMAGE"
              FAILURES=true
            fi
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
